# Generated by Django 5.0.6 on 2024-05-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ending_time',
            field=models.DateTimeField(blank=True, default='1970-01-01 12:00:00'),
        ),
        migrations.AlterField(
            model_name='event',
            name='starting_time',
            field=models.DateTimeField(blank=True, default='1970-01-01 12:00:00'),
        ),
    ]
